#ifndef PLAYER_EFFECTS_EFFECTS_TYPES_H
#define PLAYER_EFFECTS_EFFECTS_TYPES_H
#define EFFECTS_DURATION_INFINITE  (-1)
#define EFFECTS_MAX_ACTIVE         EFFECT_KIND_COUNT
#define EFFECTS_MAX_AMPLIFIER       7
#define EFFECTS_HANDLE_NONE  ((effects_handle){ -1, 0 })
#endif
