#ifndef RENDER_FXAA_CONFIG_H
#define RENDER_FXAA_CONFIG_H
#define FXAA_LUMA_IN_ALPHA      1
#define FXAA_DEFAULT_EDGE_THRESHOLD     0.166f
#define FXAA_DEFAULT_EDGE_THRESHOLD_MIN 0.0833f
#define FXAA_DEFAULT_SUBPIX             0.75f
#define FXAA_MAX_SEARCH_STEPS   12
#define FXAA_QUALITY_LOW        0
#define FXAA_QUALITY_MEDIUM     1
#define FXAA_QUALITY_HIGH       2
#define FXAA_QUALITY_EXTREME    3
#define FXAA_QUALITY_COUNT      4
