#include "shadow_glsl.h"
#include "shadow_config.h"
#include "../../util/log.h"

#include <stdio.h>
#include <string.h>

const char *SHADOW_GLSL_DEPTH_VERT =
    "#version 330 core\n"
    "layout(location = 0) in vec3 a_pos;\n"
    "uniform mat4 u_light_vp;\n"
    "uniform mat4 u_model;\n"
    "void main() {\n"
    "    gl_Position = u_light_vp * u_model * vec4(a_pos, 1.0);\n"
    "}\n";

// empty body. depth gets written for free; we just dont want a color out.
const char *SHADOW_GLSL_DEPTH_FRAG =
    "#version 330 core\n"
    "void main() {}\n";

// the chunk meshes are pre-transformed to world space (model = identity) but
// entities arent, hence u_model in the vert above. the sample lib below is
// pasted into block.frag / entity.frag by the renderer's shader assembler.
const char *SHADOW_GLSL_SAMPLE_LIB =
    "// ---- csm sampling (generated by shadow_glsl) ----\n"
    "uniform sampler2DArrayShadow u_shadow_map;\n"
    "uniform mat4  u_shadow_mat[" "4" "];\n"
    "uniform float u_shadow_splits[" "4" "];\n"
    "uniform int   u_shadow_count;\n"
    "uniform int   u_shadow_on;\n"
    "uniform float u_shadow_max_dist;\n"
    "uniform float u_shadow_fade;\n"
    "uniform vec3  u_light_dir;\n"
    "uniform vec2  u_pcf_off[" "25" "];\n"
    "uniform float u_pcf_w[" "25" "];\n"
    "uniform int   u_pcf_count;\n"
    "uniform float u_pcf_texel;\n"
    "\n"
    "int csm_pick(float view_depth) {\n"
    "    for (int i = 0; i < u_shadow_count; ++i)\n"
    "        if (view_depth <= u_shadow_splits[i]) return i;\n"
    "    return u_shadow_count - 1;\n"
    "}\n"
    "\n"
    "float csm_pcf(int layer, vec3 uvz) {\n"
    "    float s = 0.0;\n"
    "    for (int i = 0; i < u_pcf_count; ++i) {\n"
    "        vec2 o = u_pcf_off[i] * u_pcf_texel;\n"
    "        s += u_pcf_w[i] *\n"
    "             texture(u_shadow_map, vec4(uvz.xy + o, float(layer), uvz.z));\n"
    "    }\n"
    "    return s;\n"
    "}\n"
    "\n"
    "// world_pos: fragment world position. n: world normal. view_depth: linear\n"
    "// distance from camera along view axis. returns visibility, 1 = lit.\n"
    "float csm_visibility(vec3 world_pos, vec3 n, float view_depth) {\n"
    "    if (u_shadow_on == 0) return 1.0;\n"
    "    if (view_depth >= u_shadow_max_dist) return 1.0;\n"
    "\n"
    "    int layer = csm_pick(view_depth);\n"
    "    // normal-offset bias: push the sample off the surface, more at grazing\n"
    "    float ndl = max(dot(n, -u_light_dir), 0.0);\n"
    "    float nb  = (1.0 - ndl) * 0.05 + 0.01;\n"
    "    vec4 lp = u_shadow_mat[layer] * vec4(world_pos + n * nb, 1.0);\n"
    "    vec3 uvz = lp.xyz / lp.w;\n"
    "    if (uvz.z > 1.0) return 1.0;          // beyond far plane = lit\n"
    "    uvz.z -= 0.0015;                      // constant depth bias\n"
    "\n"
    "    float vis = csm_pcf(layer, uvz);\n"
    "\n"
    "    // cross-fade into the next cascade across the split band\n"
    "    if (layer + 1 < u_shadow_count) {\n"
    "        float edge = u_shadow_splits[layer];\n"
    "        float band = edge * u_shadow_fade;\n"
    "        float t = clamp((view_depth - (edge - band)) / max(band, 1e-4), 0.0, 1.0);\n"
    "        if (t > 0.0) {\n"
    "            vec4 lp2 = u_shadow_mat[layer + 1] * vec4(world_pos + n * nb, 1.0);\n"
    "            vec3 uvz2 = lp2.xyz / lp2.w;\n"
    "            uvz2.z -= 0.0015;\n"
    "            float vis2 = (uvz2.z > 1.0) ? 1.0 : csm_pcf(layer + 1, uvz2);\n"
    "            vis = mix(vis, vis2, t);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    // fade the whole thing out near max distance\n"
    "    float fade = clamp((u_shadow_max_dist - view_depth) /\n"
    "                       (u_shadow_max_dist * u_shadow_fade), 0.0, 1.0);\n"
    "    return mix(1.0, vis, fade);\n"
    "}\n";

static int write_if_changed(const char *path, const char *src) {
    // read existing, skip the write if identical. avoids touching mtime and
    // re-triggering any file watcher we might bolt on later.
    FILE *r = fopen(path, "rb");
    if (r) {
        fseek(r, 0, SEEK_END);
        long n = ftell(r);
        fseek(r, 0, SEEK_SET);
        if (n == (long)strlen(src)) {
            char buf[8192];
            if (n < (long)sizeof buf && fread(buf, 1, (size_t)n, r) == (size_t)n) {
                buf[n] = 0;
                if (strcmp(buf, src) == 0) { fclose(r); return 1; }
            }
        }
        fclose(r);
    }
    FILE *w = fopen(path, "wb");
    if (!w) { LOGE("shadow_glsl: cant write %s", path); return 0; }
    fputs(src, w);
    fclose(w);
    return 1;
}

int shadow_glsl_write(const char *dir) {
    char vp[256], fp[256];
    snprintf(vp, sizeof vp, "%s/shadow_depth.vert", dir);
    snprintf(fp, sizeof fp, "%s/shadow_depth.frag", dir);

    int ok = write_if_changed(vp, SHADOW_GLSL_DEPTH_VERT);
    ok    &= write_if_changed(fp, SHADOW_GLSL_DEPTH_FRAG);
    if (ok) LOGI("shadow_glsl: depth shaders stamped to %s", dir);
    return ok;
}
